version: 2
updates:
# Create PRs for github.com/quic-go/quic-go dependency updates
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 5
  allow:
  - dependency-name: "github.com/quic-go/quic-go"
# Create PRs for golang version updates
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily