version = 1
SPDX-PackageName = "Gardener fork of mvladev/quic-reverse-http-tunnel"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/quic-reverse-http-tunnel"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors to the Gardener project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors to the Gardener project"
SPDX-License-Identifier = "CC-BY-4.0"
