name: quic-reverse-http-tunnel image

on:
  release:
    types:
    - published
  push:
    branches:
    - main
    tags:
    - v*
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ghcr.io/${{ github.repository_owner }}/quic-reverse-http-tunnel/quic-client
            target: quic-client
          - image: ghcr.io/${{ github.repository_owner }}/quic-reverse-http-tunnel/quic-client-tcp
            target: quic-client-tcp
          - image: ghcr.io/${{ github.repository_owner }}/quic-reverse-http-tunnel/quic-server
            target: quic-server
    steps:
    - uses: actions/checkout@v4

    - name: Docker meta
      uses: docker/metadata-action@v3
      id: meta
      with:
        images: ${{ matrix.image }}
        tags: |
          type=semver,pattern={{raw}}
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=sha
        flavor: |
          latest=${{ github.ref == 'refs/heads/main' }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        target: ${{ matrix.target }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}